### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by vangheem** [collective/collective.siteisolation#5]
@mpeeters @gotcha @jfroche could you make a new release or give me rights to do so? This package requires a zcml slug still.

**Comment by gotcha** [comment]
Being explicit about zcml is important imo: http://bubblenet.be/blog/lets-get-rid-of-z3c.autoinclude

Rather than making a slug in buildout, add `<include package="collective.siteisolation" />` in your Plone policy.
IOW, I'd rather not make a new release.

**Comment by vangheem** [comment]
Pretty annoying for site integrators who just want to install an addon. I think you might be a bit overzealous about the explicit vs implicit.

I ask this because I was helping someone install this and it took him a long time to just install it. This was one of the problems.

**Comment by gotcha** [comment]
IMO, when trying to make Plone easier to approach, z3c.autoinclude went a step too far.

My main issue with z3c.autoinclude is that there is currently no way to avoid the problem it causes. Can we rethink how to avoid the need to declare packages both in egg and zcml section without causing the problems mentioned in my post ?
